"""test alembic command

Revision ID: 5e6ead7f79fe
Revises: 6a79324adb59
Create Date: 2025-11-13 11:13:18.540855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e6ead7f79fe'
down_revision = '6a79324adb59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
