"""test alembic format util

Revision ID: 553ad0484a9d
Revises: 5e6ead7f79fe
Create Date: 2025-11-13 11:18:33.627900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553ad0484a9d'
down_revision = '5e6ead7f79fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
